[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
fastReruns = true

[ui]
hideTopBar = false
hideSidebarNav = false

[client]
showErrorDetails = true
toolbarMode = "auto"

[global]
developmentMode = false
logLevel = "warning"

[logger]
level = "info"

[feature]
USE_ENHANCED_AGENT = true 